name: Mozaldol API CI

on:
  push:
    branches: ["teste-github-actions"]

jobs:
  first_job:
    name: Meu primeiro Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restaurar dependências
        run: dotnet restore

      - name: Buildar o projeto
        run: dotnet build --configuration Release --no-restore