name: Mozaldol API CI

on:
  push:
    branches: ["teste-github-actions"]

jobs:
  first_job:
    name: Meu primeiro Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restaurar dependências
        run: dotnet restore

      - name: Buildar o projeto
        run: dotnet build --configuration Release --no-restore

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Login with GCP
        run: gcloud auth login

      - name: Configure Docker for GCP
        run: |
          gcloud auth configure-docker southamerica-east1-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build -t southamerica-east1-docker.pkg.dev/mozaodol/mozaodol-hub/mozaodol-api .

      - name: Push Docker Image to Artifact Registry
        run: |
          docker push southamerica-east1-docker.pkg.dev/mozaodol/mozaodol-hub/mozaodol-api